# Información del proyecto
sonar.projectKey=com.universidad.pedidosu11
sonar.projectName=Pedidos U11 - Refactorización
sonar.projectVersion=1.0.0

# Código fuente
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# # Excluir generados automáticamente
# sonar.exclusions=**/model/*.java, **/repository/*.java
# sonar.coverage.exclusions=**/model/*.java, **/repository/*.java

# Encoding
sonar.sourceEncoding=UTF-8

# Java específico
sonar.java.source=21
sonar.java.target=21

# Host de SonarQube
sonar.host.url=http://localhost:9000
